---
title: "Dataset descriptive stats"
author: 
- Petra Hermankova^[Aarhus University, Denmark, https://orcid.org/0000-0002-6349-0540]
date: "`r format(Sys.Date())`"
output:
  html_document:
    theme: united
    toc: yes
    toc_float: true
    number_sections: true
    toc_depth: 3
    df_print: paged
---

# Initial setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(sf)
library(sfarrow)
library(tidyverse)
library(jsonlite)
library(tidyr)
library(ggplot2)
library(viridis)
```

```{r loading data}
getwd()
LISTjson <- fromJSON("../../data/large_data/LIST_occupsorgs_industry_people_20231206.json") # with people, Harris cats
LIST <- as_tibble(LISTjson)
```

# Full dataset

## Total number
```{r}
# all inscriptions contained in the dataset
nrow(LIST)
```
## Dates

Need to join with the original dataset that does not contain occupational data, but it contains dates.

```{r}
LISTorig <- st_read_parquet("../../data/large_data/LIST_v1-0.parquet")
nrow(LISTorig)

names(LISTorig)
LISTorig <- rename(LISTorig, c("LIST-ID" = "LIST.ID")) # renaming the column


LIST$`LIST-ID` <- as.data.frame(LIST$`LIST-ID`)
```

```{r}
LISTall<- left_join(LISTorig, LIST, by = "LIST-ID")
```



```{r}
names(LISTall)
```


```{r}
# earliest inscription

datesall<- LISTall %>% 
  select(not_before, not_after) 

table(datesall$not_before) # -750

# latest inscription

table(datesall$not_after) # 2230 that is clearly non-sense

# how many were agter 476 AD

datesall %>% 
  filter(not_after > 800) %>% 
  View() # 24491 inscr after 476 AD with some nonsensical


LISTall %>% 
  filter(not_after > 2000) %>% 
  View()

# typos in the data!!!

```
# Types of inscriptions

```{r}
LIST %>% 
  select(type_of_inscription_auto, ) %>% 
  unlist() %>% 
  table()

# 189639 epitaphs = 

189639 / (nrow(LIST) / 100)


```


# Occupational subset

## Basic overview

```{r}
occups<- read_csv("LISTsample_occups.csv")
```


```{r}
# how many instances of occupations 
length(unlist(LIST$occups))

nrow(occups) # alternative way, should be the same number

```
```{r}
# how many inscriptions with occupations (possible multiple per inscription)

length(unique(occups$`LIST-ID`))
```

```{r}
# how many of those type


```

```{r}
# how many occupations occur on inscription (counting the multiple occurrences on inscriptions)
table(unlist(LIST$occups_N))

# min 0, max 30
```




```{r}
# how many unique occupations there are
length(unique(unlist(LIST$occups)))

length(unique(occups$occups)) # alternative way, should be the same number

```
```{r}
# counts by occupation

sort(table(occups$occups))

```
```{r}
# ratio of inscr types by inscr with occupation

 

```

